version: "3.9"

services:
  dev:
    build: .
    container_name: cuda-dev
    working_dir: /app
    volumes:
      - ./:/app
      - ./cache/pip:/root/.cache/pip
    stdin_open: true
    tty: true
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    command: >
      bash -c '
        set -euo pipefail;
        if [ ! -d scripts ]; then
          echo "ERROR: brak katalogu scripts/"; exit 1;
        fi;
        cd scripts;
        shopt -s nullglob;
        files=(*.sh);
        if [ $${#files[@]} -eq 0 ]; then
          echo "Brak skryptów *.sh w scripts/"; exit 0;
        fi;
        for f in "$${files[@]}"; do
          echo "Running $$f with argument cuda...";
          chmod +x "$$f" || true;
          bash "$$f" cuda;
        done
      '
